print('hello python')
x=raw_input('input something: ')
print('you typed: '+x)
x=input('input an expression: ')
print('the answer is: '+str(x))
myfile=open('file','a')
print(myfile.name)
print(myfile.mode)
print(myfile.closed)
myfile.write('!!!\n')
myfile.close()
myfile=open('file','r')
for word in myfile.readlines():
	print(word)
print(myfile.read(0))
print(myfile.tell())